package salesagua;

/**
 *
 * @author User
 */
public class SalEsAgua extends javax.swing.JFrame {
//DECLARAR VARIABLES..
    double litros, detergente,densidad,agua,sales;
    String TXTagua, TXTsales;
    
    public SalEsAgua() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        slLitros = new javax.swing.JSlider();
        lblLitros = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        slDetergente = new javax.swing.JSlider();
        lblDetergente = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        slDensidad = new javax.swing.JSlider();
        lblDensidad = new javax.swing.JLabel();
        lblAgua = new javax.swing.JLabel();
        lblSales = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Litros a fabricar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        slLitros.setMinimum(1);
        slLitros.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slLitrosStateChanged(evt);
            }
        });

        lblLitros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(slLitros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(lblLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(slLitros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calidad de detergente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        slDetergente.setMaximum(10);
        slDetergente.setValue(5);
        slDetergente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slDetergenteStateChanged(evt);
            }
        });

        lblDetergente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(slDetergente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDetergente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(slDetergente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblDetergente, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Densidad deseada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        slDensidad.setMaximum(200);
        slDensidad.setMinimum(50);
        slDensidad.setValue(100);
        slDensidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slDensidadStateChanged(evt);
            }
        });

        lblDensidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(slDensidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDensidad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(slDensidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDensidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        lblAgua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSales, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgua, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(lblSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slLitrosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slLitrosStateChanged
       //Declarar variable que almacena el valor slider
       String TXTlitros;
       //Asignar a la cadena de texto (TXT) el valor de slider que ha sido convertido a String
       TXTlitros =String.valueOf(slLitros.getValue());
       //Colocar valor en su respectivo label
       lblLitros.setText(TXTlitros);
       
       //ASIGNAR A LAS VARIABLES TIPO DOBLE RESPECTIVO VALOR,ASIGNADO POR SUS SLIDER´S
    litros = slLitros.getValue();
    detergente = slDetergente.getValue();
    densidad =  slDensidad.getValue();
    //ASIGNAR LA VARIABLE ´AGUA´ Y A ´SALES´ SU RESPECTIVO VALOR
    agua = (2*(litros))+(detergente/densidad);
    sales = ((detergente*litros))/((100*densidad));
    //CONVERTIR LOS VALORES ENTEROS (INT) DE ´AGUA´ Y ´SALES´ A CADENA DE TEXTO (String)
    TXTagua =String.valueOf(agua);
    TXTsales = String.valueOf(sales);
    //COLOCAR LAS VARIABLES String (TXT) EN SUS RESPECTIVAS Label´s
    lblAgua.setText(TXTagua);
    lblSales.setText(TXTsales);
    }//GEN-LAST:event_slLitrosStateChanged

    private void slDetergenteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slDetergenteStateChanged
        // TODO add your handling code here:
        String TXTDetergente;
        //Asignar a la cadena de texto (TXT) el valr del slider que ha sido convertido a String 
        TXTDetergente = String.valueOf(slDetergente.getValue());
        lblDetergente.setText(TXTDetergente);
        
        //ASIGNAR A LAS VARIABLES TIPO DOBLE RESPECTIVO VALOR,ASIGNADO POR SUS SLIDER´S
    litros = slLitros.getValue();
    detergente = slDetergente.getValue();
    densidad =  slDensidad.getValue();
    //ASIGNAR LA VARIABLE ´AGUA´ Y A ´SALES´ SU RESPECTIVO VALOR
    agua = (2*(litros))+(detergente/densidad);
    sales = ((detergente*litros))/((100*densidad));
    //CONVERTIR LOS VALORES ENTEROS (INT) DE ´AGUA´ Y ´SALES´ A CADENA DE TEXTO (String)
    TXTagua =String.valueOf(agua);
    TXTsales = String.valueOf(sales);
    //COLOCAR LAS VARIABLES String (TXT) EN SUS RESPECTIVAS Label´s
    lblAgua.setText(TXTagua);
    lblSales.setText(TXTsales);
    }//GEN-LAST:event_slDetergenteStateChanged

    private void slDensidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slDensidadStateChanged
        // TODO add your handling code here:
        String TXTDensidad;
        //Asignar a la cadena de texto (TXT) el valr del slider que ha sido convertida a String
        TXTDensidad = String.valueOf(slDensidad.getValue());
        lblDensidad.setText(TXTDensidad);
        
        //ASIGNAR A LAS VARIABLES TIPO DOBLE RESPECTIVO VALOR,ASIGNADO POR SUS SLIDER´S
    litros = slLitros.getValue();
    detergente = slDetergente.getValue();
    densidad =  slDensidad.getValue();
    //ASIGNAR LA VARIABLE ´AGUA´ Y A ´SALES´ SU RESPECTIVO VALOR
    agua = (2*(litros))+(detergente/densidad);
    sales = ((detergente*litros))/((100*densidad));
    //CONVERTIR LOS VALORES ENTEROS (INT) DE ´AGUA´ Y ´SALES´ A CADENA DE TEXTO (String)
    TXTagua =String.valueOf(agua);
    TXTsales = String.valueOf(sales);
    //COLOCAR LAS VARIABLES String (TXT) EN SUS RESPECTIVAS Label´s
    lblAgua.setText(TXTagua);
    lblSales.setText(TXTsales);
    }//GEN-LAST:event_slDensidadStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalEsAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalEsAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalEsAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalEsAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalEsAgua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAgua;
    private javax.swing.JLabel lblDensidad;
    private javax.swing.JLabel lblDetergente;
    private javax.swing.JLabel lblLitros;
    private javax.swing.JLabel lblSales;
    private javax.swing.JSlider slDensidad;
    private javax.swing.JSlider slDetergente;
    private javax.swing.JSlider slLitros;
    // End of variables declaration//GEN-END:variables
}
